site_name: Hasan's Route
site_url: https://HasanByt.github.io/HowToCloudflare
theme:
  name: material
  language: de
  palette:
    scheme: default
    primary: blue
    accent: light blue
nav:
  - Startseite: index.md
  - Anleitung:
      - How to Cloudflare: HowToCloudfare.md
      - How to SSH(Server): HowToSSH(Server).md
      - How to SSH.md: HowToSSH.md
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
